=== SalmaOuksir/ProjetFinModule/PROJET_XML_WS_SALMA/PartieA/Releve.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" > 
  <xsd:element name="releve">
      <xsd:complexType>
          <xsd:sequence>
              <xsd:element name="datereleve" type="xsd:date" />
              <xsd:element name="solde" type="xsd:unsignedShort" />
              <xsd:element name="operations">
                  <xsd:complexType>
                      <xsd:sequence>
                          <xsd:element maxOccurs="unbounded" name="operation">
                              <xsd:complexType>
                                  <xsd:attribute name="type" use="required">
                                      <xsd:simpleType>
                                          <xsd:restriction base="xsd:string">
                                              <xsd:enumeration value="CREDIT"/>
                                              <xsd:enumeration value="DEBIT"/>
                                          </xsd:restriction>
                                      </xsd:simpleType>
                                  </xsd:attribute>                  
                                  <xsd:attribute name="date" type="xsd:date" use="required" />
                                  <xsd:attribute name="montant" use="required" >
                                     <xsd:simpleType>
                                         <xsd:restriction base="xsd:double">
                                             <xsd:minInclusive value="1"></xsd:minInclusive>
                                         </xsd:restriction>
                                     </xsd:simpleType> 
                                  </xsd:attribute>
                                  <xsd:attribute name="description" type="xsd:string" use="required" />
                              </xsd:complexType>
                          </xsd:element>
                      </xsd:sequence>
                      <xsd:attribute name="datedebut" type="xsd:date" use="required" />
                      <xsd:attribute name="datefin" type="xsd:date" use="required" />
                  </xsd:complexType>
              </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="rib" type="xsd:string" use="required" />
      </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== SalmaOuksir/ProjetFinModule/PROJET_XML_WS_SALMA/PartieA/Releve2.xml
<?xml version="1.0" encoding="UTF-8"?>
<releve xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/HP/Desktop/ProjetFinModule/Releve.xsd" rib="011112222333344445555666">
    <datereleve>2021-11-10</datereleve>
    <solde>14500</solde>
    <operations datedebut="2021-01-01" datefin="2021-01-30">
        <operation type="CREDIT" date="2021-01-01" montant="9000" description="Vers Espèce"/>
        <operation type="DEBIT" date="2021-01-11" montant="3400" description="Chèque Guichet"></operation>
        <operation type="DEBIT" date="2021-01-15" montant="120" description="Prélèvement Assurence"></operation>
        <operation type="CREDIT" date="2021-01-25" montant="70000" description="Virement "></operation>
    </operations>
</releve>
